spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/giftlist1
    username: postgres
    password: almaz2002
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger
app:
  jwt:
    secretWord: veryveryveryveryveryveryveryveryveryversecretword
    expiredAt: 1
server:
  error:
    include-message: always